_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.9.15
        t:
            "1":
                - 3
                - 55
            "2":
                - 3
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.9.15
            "5": 0.19.8
            "8":
                - 3
                - 5
            "12": 0.19.8
            "13": windows-amd64
batch_size:
    value: 128
epochs:
    value: 20
hidden_layers:
    value:
        - 1024
        - 512
        - 256
lambtha:
    value: 1e-05
latent_dim:
    value: 256
learning_rate:
    value: 0.001
